# Uncomment the next line to define a global platform for your project
platform :ios, '12.1'

target 'ArtistHunt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ArtistHunt
  pod 'SkyFloatingLabelTextField', '~> 3.0'
  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'KeychainSwift', '~> 13.0'
  pod 'RealmSwift', '~> 3.13'
  pod 'Nuke', '~> 7.0'
  pod 'YPImagePicker'


  target 'ArtistHuntTests' do
    inherit! :search_paths
    use_frameworks!
    pod 'RealmSwift', '~> 3.13'    # Pods for testing
  end

  target 'ArtistHuntUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
